def draw_library(shelves = 3):
    print("__________==_________==______________________"+ 8*(shelves-1)*"_" +"__")
    print("|     |f d|      |s |    |s |    |s |  "+ shelves*"  |s |  " + "|")
    print("\     |r e|      |h |    |h |    |h |  "+ shelves*"  |h |  " + "|")
    print("/     |o s|      |e |    |e |    |e |  "+ shelves*"  |e |  " + "|")
    print("|     |n k|      |l |    |l |    |l |  "+ shelves*"  |l |  " + "|")
    print("|     |t__|      |f |    |f |    |f |  "+ shelves*"  |f |  " + "|")
    print("|                                            "+ 8*(shelves-1)*" " +"  |")
    print("|          ______          __________        "+ 8*(shelves-1)*" " +"  |")
    print("|         | help |        |    work  |       "+ 8*(shelves-1)*" " +"  |")
    print("|         |_desk_|        |____table_|       "+ 8*(shelves-1)*" " +"  |")
    print("|                                            "+ 8*(shelves-1)*" " +"  |")
    print("|    _____                                   "+ 8*(shelves-1)*" " +"  |")
    print("|   | w t |      |s |    |s |    |s |  "+ shelves*"  |s |  " + "|")
    print("|   |_o_a_|      |h |    |h |    |h |  "+ shelves*"  |h |  " + "|")
    print("|   | r b |      |e |    |e |    |e |  "+ shelves*"  |e |  " + "|")
    print("|   |_k_l_|      |l |    |l |    |l |  "+ shelves*"  |l |  " + "|")
    print("|   |   e |      |f |    |f |    |f |  "+ shelves*"  |f |  " + "|")
    print("|   |___s_|      |  |    |  |    |  |  "+ shelves*"  |  |  " + "|")
    print("|                                            "+ 8*(shelves-1)*" " +"  |")
    print("|____________________________________________"+ 8*(shelves-1)*"_" +"__|")
    return
